language: node_js
node_js:
  - "node"

install:
  - yarn

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^deploy-.*$/

cache:
  yarn

script:
  - yarn test
  - yarn run cypress:run
  - yarn postinstall