language: node_js
node_js:
  - "node"
  - "8"

install:
  - yarn

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^deploy-.*$/

cache:
  yarn

before_script:
  - yarn start -- --silent &

script:
  - yarn test
  - yarn run cypress