language: node_js
node_js:
  - "node"
  - "8"

install:
  - yarn

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^deploy-.*$/

cache:
  yarn
  directories:
    - ~/.npm
    - ~/.cache
    - ~/node_modules

script:
  - $(yarn bin)/cypress run --record